[package]
name = "alexa-virtual-button"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_runtime = "0.9.1"
tokio = { version = "1.36.0", features = ["default", "macros"] }
serde_json = "1.0.113"
